keys:
  - &nix-darwin age10z776utsv2h97fwq93q2cqxqdvjmt7f4ffcrq582yj2qtnft796q879gn6
  - &proxmox_vm age1p5zqt5xclvfy5h78euuql7un9ujjprxz632wf0kgt8nt5cxvwu3stqvu3j
  - &drew-lin-desktop age1hu4du8pygnmadptmvurw6s06rpmrj9tfe7k89yejajxynp743ufqrfz5ue
  - &drew-lin-laptop age1fnmjdgpkmxxgjqrg47mue4nn5gpa5sz33rugfw9fs9flgcw0yc0sh2rfve
  - &drew-lin-laptop_gpg 2D49CE7ECE147DBA52E186CF20344D795FC6AE45
  - &do-nixos age1xyxvm55l6lhmkuxcuqhylqwq9vw5f04c8jwkxtncry7kw4hnkv3qaevc00
creation_rules:
  - path_regex: etc/nix-darwin/*
    key_groups:
    - age:
      - *nix-darwin
  - path_regex: etc/nixos/proxmox_vm/*
    key_groups:
    - age:
      - *proxmox_vm
  - path_regex: etc/nixos/desktop/*
    key_groups:
    - age:
      - *drew-lin-desktop
  - path_regex: etc/nixos/laptop/*
    key_groups:
    - age:
      - *drew-lin-laptop
      pgp: 
      - *drew-lin-laptop_gpg
  - path_regex: etc/nixos/digital-ocean/*
    key_groups:
    - age:
      - *drew-lin-desktop
      - *drew-lin-laptop
      - *do-nixos

