font: "Sans 12"

menu:
  - key: g
    desc: "Gemini"
    cmd: "~/.config/hypr/wlr-which-key/add-tab-or-new-window.sh https://gemini.google.com"
  - key: t
    desc: "Triliumnotes"
    cmd: "~/.config/hypr/wlr-which-key/add-tab-or-new-window.sh https://triliumnotes.h.lan"
  - key: w
    desc: "Work Chromium"
    cmd: "work-chromium"
  - key: f
    desc: "Firefox"
    cmd: "~/.config/hypr/wlr-which-key/add-tab-or-new-window.sh"
