# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/47c6f308-2398-46e3-98a2-ba5b993500f4";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/47c6f308-2398-46e3-98a2-ba5b993500f4";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/47c6f308-2398-46e3-98a2-ba5b993500f4";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/media/btrfs_top" =
    { device = "/dev/disk/by-uuid/47c6f308-2398-46e3-98a2-ba5b993500f4";
      fsType = "btrfs";
    };

  fileSystems."/media/ubuntu" =
    { device = "/media/ubuntu-small.img";
      fsType = "ext4";
      options = [ "loop" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4462-1E4D";
      fsType = "vfat";
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/47c6f308-2398-46e3-98a2-ba5b993500f4";
      fsType = "btrfs";
      options = [ "subvol=swap" "noatime" ];
    };

  # swapDevices = [ ];

  swapDevices = [{
    device = "/swap/swapfile"; 
  }];

  boot.resumeDevice = "/dev/disk/by-uuid/47c6f308-2398-46e3-98a2-ba5b993500f4";
  boot.kernelParams = [ "resume_offset=11035451" ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.nebula1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
