-- Generated by nwg-displays. Converted to Hyprland Lua.

-- Acer Technologies Monitor
hl.monitor({
  output = "desc:Acer Technologies XG270HU T1TAA0018500",
  mode = "2560x1440@59.95",
  position = "3840x0",
  scale = 1.0,
})

-- LG Electronics Ultrawide (with VRR enabled)
hl.monitor({
  output = "desc:LG Electronics LG HDR WQHD+ 303NTQDDW988",
  mode = "3840x1600@59.99",
  position = "0x178",
  scale = 1.0,
  vrr = 1,
})

-- Commented out / disabled monitor templates:
-- hl.monitor({ output = "desc:Acer Technologies XG270HU T1TAA0018500", disabled = true })
-- hl.monitor({ output = "desc:LG Electronics LG HDR WQHD+ 303NTQDDW988", disabled = true })
