# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/8d6b3957-edb0-4ff5-8334-4e0c14e7252f";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  fileSystems."/mnt/btrfs_root" =
    { device = "/dev/disk/by-uuid/8d6b3957-edb0-4ff5-8334-4e0c14e7252f";
      fsType = "btrfs";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/8d6b3957-edb0-4ff5-8334-4e0c14e7252f";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/8d6b3957-edb0-4ff5-8334-4e0c14e7252f";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D98E-AA86";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/8d6b3957-edb0-4ff5-8334-4e0c14e7252f";
      fsType = "btrfs";
      options = [ "subvol=swap" "noatime" ];
    };

  fileSystems."/home/drew/.local/share/Steam" =
    { device = "/dev/disk/by-uuid/8d6b3957-edb0-4ff5-8334-4e0c14e7252f";
      fsType = "btrfs";
      options = [ "subvol=Steam" ];
    };

  fileSystems."/home/drew/.local/share/containers" =
    { device = "/dev/disk/by-uuid/8d6b3957-edb0-4ff5-8334-4e0c14e7252f";
      fsType = "btrfs";
      options = [ "subvol=home_containers" ];
    };

  fileSystems."/home/drew/.cache" =
    { device = "/dev/disk/by-uuid/8d6b3957-edb0-4ff5-8334-4e0c14e7252f";
      fsType = "btrfs";
      options = [ "subvol=home.cache" ];
    };

  ## steps to create swap device
  # sudo truncate -s 0 /swap/swapfile
  # sudo chattr +C /swap/swapfile # Disable Copy-on-Write
  # sudo btrfs property set /swap/swapfile compression none
  # sudo dd if=/dev/zero of=/swap/swapfile bs=1M count=16384 # Example: 16GB
  # sudo chmod 600 /swap/swapfile
  # sudo mkswap /swap/swapfile
  # sudo swapon /swap/swapfile

  ## calculate the resume offset 
  ## This will be the value for resume_offset
  # sudo btrfs inspect-internal map-swapfile -r /swap/swapfile

  ## validating
  # lsattr /swap/swapfile
  # ...should see ----C--- /swap/swapfile
  # sudo btrfs property get /swap/swapfile
  # ...should see compression=none or nothing
  # swapon --show
  # ...should see name of file and size allocated

  swapDevices = [{
    device = "/swap/swapfile"; 
  }];

  boot.resumeDevice = "/dev/disk/by-uuid/8d6b3957-edb0-4ff5-8334-4e0c14e7252f";
  boot.kernelParams = [ "resume_offset=34490193" ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
