{
  config,
  pkgs,
  ...
}: let
  cloned_repo = builtins.fetchGit {
    url = "https://github.com/yeltnar/nebula-ansible";
  };
in {
  system.activationScripts.setup_nebula_env = {
    text = ''

      text_to_check='# setup nebula env # ';


      dir_to_add="/home/drew/.config/extra_includes";
      file_to_add="$dir_to_add/setup_nebula_env";
      text_to_add="source $file_to_add";

      # create source'd file if not there
      cat > $file_to_add <<- EOM
        # DO NOT EDIT THIS FILE... IT IS GENERATED
        # create if not there
        if [ ! -e /var/yeltnar-nebula/.env ]; then
          echo \"create /var/yeltnar-nebula/.env? y/n\";
          read do_edit;
          if [ \"\$do_edit\" == \"y\" ]; then
            mkdir -p /var/yeltnar-nebula
            vim /var/yeltnar-nebula/.env;
          fi
        fi

        # alert missing files
        if [ ! -e /var/yeltnar-nebula/knownca.pem ]; then
          echo "!! /var/yeltnar-nebula/knownca.pem is not present";
        fi
        if [ ! -e /var/yeltnar-nebula/id_rsa ]; then
          echo "!! /var/yeltnar-nebula/id_rsa is not present";
        fi
        if [ ! -e /var/yeltnar-nebula/id_rsa.pub ]; then
          echo "!! /var/yeltnar-nebula/id_rsa.pub is not present";
        fi
      EOM

      chown drew:100 "$file_to_add";

      # create bashrc file if not there
      if [ ! -e /home/drew/.bashrc ]; then
        touch /home/drew/.bashrc;
        chown drew /home/drew/.bashrc;
      fi

      # create update_nebula dir if not there
      if [ ! -d /var/yeltnar-nebula ]; then
        mkdir -p /var/yeltnar-nebula
        chown drew /var/yeltnar-nebula;
      fi

      # create bashrc file if not there
      if [ ! -e /var/yeltnar-nebula/compare_date.sh ]; then
        cp ${cloned_repo.outPath}/compare_date.sh /var/yeltnar-nebula/compare_date.sh;
        chown drew:100 /var/yeltnar-nebula/compare_date.sh;
      fi
      # create bashrc file if not there
      if [ ! -e /var/yeltnar-nebula/process_tar.sh ]; then
        cp ${cloned_repo.outPath}/process_tar.sh /var/yeltnar-nebula/process_tar.sh;
        chown drew:100 /var/yeltnar-nebula/process_tar.sh;
      fi


      test_str=$(cat /home/drew/.bashrc | grep "$text_to_check");
      # echo $text_to_check;
      # echo $test_str;

      if [ -z "$test_str" ]; then
        echo "$text_to_check" >> /home/drew/.bashrc;
        echo "$text_to_add" >> /home/drew/.bashrc;
      fi
    '';
  };
}
